name: Deploy Client to gh-pages

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
        env:
          VITE_API_ROOT: https://monopoly-money.fly.dev
          VITE_GOOGLE_ANALYTICS_TRACKING_ID: G-3SFPXD2CWJ
          VITE_API_UNREACHABLE_ERROR_MESSAGE: "Unable to communicate with server.\nSince this is publicly hosted, we may have run out of minutes on the server.\nThis should be running again next month when the time is reset."

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/client/build
          publish_branch: gh-pages
          cname: monopoly-money.nitratine.net
          force_orphan: true # Only keep latest commit in gh-pages (to keep repo size down)
